"""Generate paper/tab_params.tex (simulation parameters and physical mapping)
from engine.Config, the main sweep spec and the codec, so the printed
parameters cannot drift from the simulated ones."""
import json
from pathlib import Path

from coding import BlockCode, K, G
from engine import Config
from mbafdm import MBAFDM

ROOT = Path(__file__).resolve().parent
PAPER = ROOT / "paper"
C0 = 299_792_458.0


def physical(fc, df, N, Ncp, kmax, ell_max, d):
    Ts = 1 / (N * df)
    lam = C0 / fc
    v = kmax * df * lam
    Tblk = (N + Ncp) * Ts
    rate = v ** 2 / (lam * d)                         # Doppler rate bound, Hz/s
    return dict(v_kmh=3.6 * v, tau_us=1e6 * ell_max * Ts, Tblk_ms=1e3 * Tblk,
                rho=rate * Tblk / df, bw_mhz=N * df / 1e6)


def main():
    spec = json.load(open(ROOT / "specs" / "e4_main.json"))
    cfg = Config(**{k: v for k, v in spec["base"].items() if k != "receivers"})
    S = MBAFDM(N=cfg.N, Ncp=cfg.Ncp, alpha_max=cfg.alpha_max, xi=cfg.xi, ell_max=cfg.ell_max)
    kp = BlockCode(S.data_idx.size).k_payload
    kd = BlockCode(S.N).k_payload
    hsr = physical(5.9e9, 1e3, cfg.N, cfg.Ncp, cfg.kappa_max, cfg.ell_max, 100.0)
    v2v = physical(60e9, 15e3, cfg.N, cfg.Ncp, 1.0, cfg.ell_max, 20.0)
    rows = [
        (r"Chirps $N$, CP $N_\mathrm{cp}$, $\beta$", f"{cfg.N}, {cfg.Ncp}, {S.beta:.4f}"),
        (r"$\alpha_{\max}$, $\xi$, $Q$, $\ell_{\max}$", f"{cfg.alpha_max}, {cfg.xi}, {S.Q}, {cfg.ell_max}"),
        (r"Guard $|\mathcal{Z}|$, pilot energy $E_\mathrm{p}$", f"{len(S.zero_set)} chirps, {S.Ep:.0f}"),
        (r"Paths $P$ (estimated, cap $P_{\max}$)", f"{cfg.P} ({cfg.P_max})"),
        (r"Delays", r"$\mathcal{U}[0,\ell_{\max}-\tfrac12]$, fractional"),
        (r"Doppler", fr"$\kappa_{{\max}}\cos\vartheta$, $\kappa_{{\max}}={cfg.kappa_max:g}$"),
        (r"Power-delay profile", fr"exponential, $\tau_\mathrm{{rms}}={cfg.tau_rms:g}$ samples"),
        (r"Frame", fr"$B={cfg.B}$ blocks"),
        (r"Code", fr"rate 1/2, $K={K}$, ({G[0]:o},{G[1]:o})$_8$, CRC-16"),
        (r"Payload per pilot / data block", f"{kp} / {kd} bits"),
        (r"CFAR $P_\mathrm{fa}$; re-acq.\ period $R$", fr"$10^{{-3}}$; {cfg.reacq_every} blocks"),
        (r"\emph{HSR}: $f_\mathrm{c}$, $\Delta f$", r"5.9\,GHz, 1\,kHz"),
        (r"\quad speed at $\kappa_{\max}$; delay spread", f"{hsr['v_kmh']:.0f}\\,km/h; {hsr['tau_us']:.1f}\\,$\\mu$s"),
        (r"\quad block; Doppler rate at 100\,m", f"{hsr['Tblk_ms']:.2f}\\,ms; {hsr['rho']:.4f} per block"),
        (r"\emph{V2V}: $f_\mathrm{c}$, $\Delta f$ ($\kappa_{\max}=1$)", r"60\,GHz, 15\,kHz"),
        (r"\quad relative speed; delay spread", f"{v2v['v_kmh']:.0f}\\,km/h; {v2v['tau_us']:.2f}\\,$\\mu$s"),
        (r"\quad block; Doppler rate at 20\,m", f"{1e3*v2v['Tblk_ms']:.1f}\\,$\\mu$s; {v2v['rho']:.5f} per block"),
    ]
    tex = ["% GENERATED by make_tables.py\n",
           "\\begin{table}[t]\n\\centering\n\\caption{Simulation Parameters and Physical Mapping}\n\\label{tab:params}\n",
           "\\footnotesize\n\\begin{tabular}{@{}ll@{}}\n\\toprule\n"]
    for a, b in rows:
        tex.append(f"{a} & {b} \\\\\n")
    tex.append("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (PAPER / "tab_params.tex").write_text("".join(tex))
    json.dump({"hsr": hsr, "v2v": v2v}, open(ROOT / "runs" / "physical_mapping.json", "w"), indent=1)
    print("".join(tex))


if __name__ == "__main__":
    main()
