"""Generate the pgfplots figures and data tables of the paper from runs/*.

Writes paper/fig_*.tex. Every coordinate comes from an artifact; nothing is
typed by hand. Run after the sweeps: python make_figures.py
"""
import json
from pathlib import Path

import numpy as np

from aggregate import summarize

ROOT = Path(__file__).resolve().parent
RUNS = ROOT / "runs"
PAPER = ROOT / "paper"

STY = {
    "geniec":     ("gray!70!black", "dashed", "none", "Perfect CSI, per-block"),
    "convda":     ("gray!70!black", "solid", "square*", "Pilot every block (data-aided)"),
    "sptrack":    ("teal!80!black", "solid", "diamond*", "Superimposed, same tracker"),
    "interp":     ("violet!80!black", "densely dashed", "x", r"Periodic pilots, best $K$"),
    "genie":      ("black", "dashed", "none", "Perfect CSI"),
    "track1":     ("red!80!black", "solid", "*", r"Proposed, $B_\mathrm{p}{=}1$"),
    "track2":     ("red!55", "solid", "o", r"Proposed, $B_\mathrm{p}{=}2$"),
    "open":       ("blue!70!black", "densely dotted", "triangle*", r"Open loop, best $B_\mathrm{p}$"),
    "sp":         ("teal!80!black", "solid", "diamond*", "Superimposed pilot"),
    "conv":       ("gray!70!black", "solid", "square*", "Embedded pilot, every block"),
    "ofdm":       ("orange!85!black", "dashdotted", "pentagon*", "OFDM, same tracker"),
}


def plot(key, pts, legend=True):
    c, ls, mk, lab = STY[key]
    coords = " ".join(f"({x:g},{y:.6g})" for x, y in pts if y is not None and np.isfinite(y))
    leg = f"\\addlegendentry{{{lab}}}\n" if legend else ""
    return (f"\\addplot[color={c}, {ls}, thick, mark={mk}, mark size=1.6pt, mark options={{solid}}] "
            f"coordinates {{{coords}}};\n{leg}")


def fig_main():
    a, _ = summarize("e4_main")
    b, _ = summarize("e4b_baselines")
    c, _ = summarize("e4c_interp")
    A1 = {r["snr_db"]: r for r in a if r.get("Bp") == 1 and "tp_conv" in r}
    A2 = {r["snr_db"]: r for r in a if r.get("Bp") == 2}
    Bb = {r["snr_db"]: r for r in b}
    Cc = {r["snr_db"]: r for r in c}
    snrs = sorted(A1)
    ol = {}
    for r in a:
        if "tp_openloop" in r:
            if r["snr_db"] not in ol or r["tp_openloop"] > ol[r["snr_db"]][0]:
                ol[r["snr_db"]] = (r["tp_openloop"], r["Bp"])
    ip = {s: max((Cc[s]["tp_interp4"], 4), (Cc[s]["tp_interp8"], 8)) for s in snrs}
    tp = {
        "genie": [(s, A1[s]["tp_genie"]) for s in snrs],
        "track1": [(s, A1[s]["tp_track"]) for s in snrs],
        "track2": [(s, A2[s]["tp_track"]) for s in snrs],
        "geniec": [(s, Bb[s]["tp_genie-conv"]) for s in snrs],
        "convda": [(s, Bb[s]["tp_conv-da"]) for s in snrs],
        "sptrack": [(s, Bb[s]["tp_sp-track"]) for s in snrs],
        "interp": [(s, ip[s][0]) for s in snrs],
        "open": [(s, ol[s][0]) for s in snrs],
        "ofdm": [(s, Bb[s]["tp_ofdm-track"]) for s in snrs],
    }
    axis = ("\\begin{axis}[%s width=\\columnwidth, height=0.66\\columnwidth, xlabel={SNR (dB)}, "
            "ylabel={Throughput (bit/s/Hz)}, grid=both, grid style={black!12}, xmin=%g, xmax=%g, ymin=0, ymax=1, "
            "legend style={font=\\scriptsize, at={(0.5,-0.24)}, anchor=north, legend columns=2, cells={anchor=west}}, "
            "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, title={%s}, title style={font=\\footnotesize}]\n")
    tex = ["% GENERATED by make_figures.py from runs/e4_main, e4b_baselines, e4c_interp (same channel draws)\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n",
           axis % ("name=a,", min(snrs), max(snrs), "(a) pilot placement")]
    for k in ("genie", "track1", "geniec", "convda", "sptrack", "interp"):
        tex.append(plot(k, tp[k]))
    tex.append("\\end{axis}\n")
    tex.append(axis.replace("\\begin{axis}[%s", "\\begin{axis}[at={(a.south west)}, anchor=north west, yshift=-3.5cm, %s")
               % ("", min(snrs), max(snrs), "(b) closing the loop, and the waveform"))
    for k in ("genie", "track1", "track2", "open", "ofdm"):
        tex.append(plot(k, tp[k]))
    tex.append("\\end{axis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Coded throughput versus SNR ($B=16$ blocks, $P=4$ paths with fractional delays, Jakes Doppler with "
               "$\\kappa_{\\max}=3$, number of paths estimated); every curve uses the same 200 channel realizations per point. "
               "(a) Where the pilot energy goes: one embedded pilot block (proposed), one in every block, periodic pilot blocks "
               "(best of $K\\in\\{4,8\\}$), or a superimposed pilot in every block. (b) What closing the loop adds over "
               "open-loop prediction (best of $B_\\mathrm{p}\\in\\{1,2,4,8\\}$), and what AFDM adds over OFDM with the same tracker.}\n"
               "\\label{fig:tp}\n\\end{figure}\n")
    (PAPER / "fig_tp.tex").write_text("".join(tex))

    bl = {
        "genie": [(s, A1[s]["bler_genie"]) for s in snrs],
        "track1": [(s, A1[s]["bler_track"]) for s in snrs],
        "convda": [(s, Bb[s]["bler_conv-da"]) for s in snrs],
        "sptrack": [(s, Bb[s]["bler_sp-track"]) for s in snrs],
        "ofdm": [(s, Bb[s]["bler_ofdm-track"]) for s in snrs],
    }
    tex = ["% GENERATED by make_figures.py from runs/e4_main, e4b_baselines (same channel draws)\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n\\begin{semilogyaxis}[width=\\columnwidth, "
           "height=0.66\\columnwidth, xlabel={SNR (dB)}, ylabel={Block error rate}, grid=both, grid style={black!12}, "
           "xmin=%g, xmax=%g, ymin=1e-3, ymax=1, legend style={font=\\scriptsize, at={(0.5,-0.24)}, anchor=north, "
           "legend columns=2, cells={anchor=west}}, tick label style={font=\\footnotesize}, label style={font=\\footnotesize}]\n"
           % (min(snrs), max(snrs))]
    for k in ("genie", "track1", "convda", "sptrack", "ofdm"):
        tex.append(plot(k, [(s, max(v, 1e-3)) for s, v in bl[k]]))
    tex.append("\\end{semilogyaxis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Block error rate of selected systems of Fig.~\\ref{fig:tp}; values below $10^{-3}$ "
               "(no error in the simulated blocks) are drawn at $10^{-3}$.}\n\\label{fig:bler}\n\\end{figure}\n")
    (PAPER / "fig_bler.tex").write_text("".join(tex))
    json.dump({"best_open": [(s, ol[s][0], ol[s][1]) for s in snrs],
               "best_interp": [(s, ip[s][0], ip[s][1]) for s in snrs]}, open(RUNS / "fig_main_meta.json", "w"))


def fig_frame():
    res, _ = summarize("e5_frame")
    tex = ["% GENERATED by make_figures.py from runs/e5_frame.jsonl\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n"
           "\\begin{semilogxaxis}[width=\\columnwidth, height=0.72\\columnwidth, xlabel={Frame length $B$ (blocks)}, "
           "ylabel={Throughput (bit/s/Hz)}, log basis x=2, grid=both, grid style={black!12}, ymin=0, ymax=1, "
           "legend style={font=\\scriptsize, at={(0.5,-0.2)}, anchor=north, legend columns=2, cells={anchor=west}}, "
           "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}]\n"]
    for snr, fill in ((12, True), (6, False)):
        rr = sorted([r for r in res if r["snr_db"] == snr], key=lambda r: r["B"])
        for key, field in (("genie", "tp_genie"), ("track1", "tp_track"), ("open", "tp_openloop"), ("conv", "tp_conv")):
            c, ls, mk, lab = STY[key]
            mk2 = mk if fill else mk.replace("*", "")
            coords = " ".join(f"({r['B']},{r[field]:.6g})" for r in rr)
            tex.append(f"\\addplot[color={c}, {ls}, thick, mark={mk2}, mark size=1.6pt, mark options={{solid}}] "
                       f"coordinates {{{coords}}};\n")
            if fill:
                if key == "open":
                    lab = r"Open loop, $B_\mathrm{p}{=}1$"      # E5 uses one pilot block for every receiver
                tex.append(f"\\addlegendentry{{{lab}}}\n")
    tex.append("\\end{semilogxaxis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Throughput versus frame length with one pilot block. Filled markers: 12\\,dB; "
               "open markers: 6\\,dB. Each point averages 100 channel realizations.}\n"
               "\\label{fig:frame}\n\\end{figure}\n")
    (PAPER / "fig_frame.tex").write_text("".join(tex))


def fig_theory():
    th = json.load(open(RUNS / "theory_check.json"))
    e2, e3 = th["e2"], th["e3"]
    cols = {1: "red!80!black", 2: "blue!70!black", 4: "teal!80!black"}
    tex = ["% GENERATED by make_figures.py from runs/theory_check.json\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n"
           "\\begin{axis}[name=a, width=\\columnwidth, height=0.6\\columnwidth, xlabel={Per-block pilot SNR $\\gamma_1$ (dB)}, "
           "ylabel={$P_\\mathrm{cell}$}, grid=both, grid style={black!12}, ymin=0, ymax=1.02, "
           "legend style={font=\\scriptsize, at={(0.99,0.02)}, anchor=south east}, legend columns=2, "
           "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, title={(a) acquisition, Prop.~\\ref{prop:acq}}, "
           "title style={font=\\footnotesize}]\n"]
    for Bp in (1, 2, 4):
        rr = sorted([r for r in e2 if r["Bp"] == Bp], key=lambda r: r["gamma1_db"])
        tex.append(f"\\addplot[color={cols[Bp]}, only marks, mark=*, mark size=1.5pt] coordinates {{"
                   + " ".join(f"({r['gamma1_db']},{r['p_cell']:.4f})" for r in rr) + "};\n")
        tex.append(f"\\addlegendentry{{sim. $B_\\mathrm{{p}}{{=}}{Bp}$}}\n")
        tex.append(f"\\addplot[color={cols[Bp]}, thick] coordinates {{"
                   + " ".join(f"({r['gamma1_db']},{r['p_cell_formula']:.4f})" for r in rr) + "};\n")
        tex.append(f"\\addlegendentry{{\\eqref{{eq:pcell}}}}\n")
    tex.append("\\end{axis}\n")
    tex.append("\\begin{semilogyaxis}[at={(a.south west)}, anchor=north west, yshift=-1.75cm, width=\\columnwidth, "
               "height=0.62\\columnwidth, xlabel={Predicted block $b'$}, ylabel={Prediction NMSE}, grid=both, "
               "grid style={black!12}, legend style={font=\\scriptsize, at={(0.99,0.02)}, anchor=south east}, legend columns=2, "
               "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, "
               "title={(b) prediction, Theorem~\\ref{thm:pred}, $\\gamma_1=20$\\,dB}, title style={font=\\footnotesize}]\n")
    for r in e3:
        if r["gamma1_db"] != 20:
            continue
        Bp = r["Bp"]
        tex.append(f"\\addplot[color={cols[Bp]}, only marks, mark=*, mark size=1.3pt] coordinates {{"
                   + " ".join(f"({b},{v:.4g})" for b, v in zip(r["lag"], r["ol_emp"])) + "};\n")
        tex.append(f"\\addlegendentry{{open loop $B_\\mathrm{{p}}{{=}}{Bp}$}}\n")
        # the linearized bound is meaningful only for small errors: draw it while <= 1
        tex.append(f"\\addplot[color={cols[Bp]}, thick] coordinates {{"
                   + " ".join(f"({b},{v:.4g})" for b, v in zip(r["lag"], r["ol_formula"]) if v <= 1) + "};\n")
        tex.append("\\addlegendentry{\\eqref{eq:pred_bound}}\n")
    r1 = [r for r in e3 if r["gamma1_db"] == 20 and r["Bp"] == 1][0]
    tex.append("\\addplot[color=black, only marks, mark=square*, mark size=1.3pt] coordinates {"
               + " ".join(f"({b},{v:.4g})" for b, v in zip(r1["tr_block"], r1["tr_emp"])) + "};\n")
    tex.append("\\addlegendentry{tracked $B_\\mathrm{p}{=}1$}\n")
    tex.append("\\addplot[color=black, thick] coordinates {"
               + " ".join(f"({b},{v:.4g})" for b, v in zip(r1["tr_block"], r1["tr_formula"])) + "};\n")
    tex.append("\\addlegendentry{\\eqref{eq:pred_bound}}\n")
    tex.append("\\addplot[black!50, densely dashed, domain=0:32] {2};\n")
    tex.append("\\end{semilogyaxis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Validation of the analysis for a single path (markers: simulation; lines: closed forms). "
               "(a) Correct-cell probability of acquisition. (b) NMSE of the predicted path coefficient for open-loop "
               "prediction from $B_\\mathrm{p}$ pilot blocks and for one-step prediction while tracking with correct decisions; the bound is drawn where it is below one, and the dashed line marks the level 2 of a uniformly random phase, at which open-loop prediction saturates.}\n"
               "\\label{fig:theory}\n\\end{figure}\n")
    (PAPER / "fig_theory.tex").write_text("".join(tex))


if __name__ == "__main__":
    import sys
    for f in (sys.argv[1:] or ["theory", "main", "frame"]):
        try:
            {"theory": fig_theory, "main": fig_main, "frame": fig_frame}[f]()
            print(f, "ok")
        except Exception as e:  # noqa: BLE001
            print(f, "FAILED:", repr(e))
