"""Generate paper/tab_params.tex (simulation parameters and physical mapping)
from engine.Config, the main sweep spec and the codec, so the printed
parameters cannot drift from the simulated ones."""
import json
from pathlib import Path

from coding import BlockCode, K, G
from engine import Config
from mbafdm import MBAFDM

ROOT = Path(__file__).resolve().parent
PAPER = ROOT / "paper"
C0 = 299_792_458.0


def physical(fc, df, N, Ncp, kmax, ell_max, d):
    Ts = 1 / (N * df)
    lam = C0 / fc
    v = kmax * df * lam
    Tblk = (N + Ncp) * Ts
    rate = v ** 2 / (lam * d)                         # Doppler rate bound, Hz/s
    return dict(v_kmh=3.6 * v, tau_us=1e6 * ell_max * Ts, Tblk_ms=1e3 * Tblk,
                rho=rate * Tblk / df, bw_mhz=N * df / 1e6)


def main():
    spec = json.load(open(ROOT / "specs" / "e4_main.json"))
    cfg = Config(**{k: v for k, v in spec["base"].items() if k != "receivers"})
    S = MBAFDM(N=cfg.N, Ncp=cfg.Ncp, alpha_max=cfg.alpha_max, xi=cfg.xi, ell_max=cfg.ell_max)
    kp = BlockCode(S.data_idx.size).k_payload
    kd = BlockCode(S.N).k_payload
    hsr = physical(5.9e9, 1e3, cfg.N, cfg.Ncp, cfg.kappa_max, cfg.ell_max, 100.0)
    v2v = physical(60e9, 15e3, cfg.N, cfg.Ncp, 1.0, cfg.ell_max, 20.0)
    rows = [
        (r"Chirps $N$, CP $N_\mathrm{cp}$, $\beta$", f"{cfg.N}, {cfg.Ncp}, {S.beta:.4f}"),
        (r"$\alpha_{\max}$, $\xi$, $Q$, $\ell_{\max}$", f"{cfg.alpha_max}, {cfg.xi}, {S.Q}, {cfg.ell_max}"),
        (r"Guard $|\mathcal{Z}|$, pilot energy $E_\mathrm{p}$", f"{len(S.zero_set)} chirps, {S.Ep:.0f}"),
        (r"Paths $P$ (estimated, cap $P_{\max}$)", f"{cfg.P} ({cfg.P_max})"),
        (r"Delays", r"$\mathcal{U}[0,\ell_{\max}-\tfrac12]$, fractional"),
        (r"Doppler", fr"$\kappa_{{\max}}\cos\vartheta$, $\kappa_{{\max}}={cfg.kappa_max:g}$"),
        (r"Power-delay profile", fr"exponential, $\tau_\mathrm{{rms}}={cfg.tau_rms:g}$ samples"),
        (r"Frame", fr"$B={cfg.B}$ blocks"),
        (r"Code", fr"rate 1/2, $K={K}$, ({G[0]:o},{G[1]:o})$_8$, CRC-16"),
        (r"Payload per pilot / data block", f"{kp} / {kd} bits"),
        (r"CFAR $P_\mathrm{fa}$; re-acq.\ period $R$", fr"$10^{{-3}}$; {cfg.reacq_every} blocks"),
        (r"\emph{HSR}: $f_\mathrm{c}$, $\Delta f$", r"5.9\,GHz, 1\,kHz"),
        (r"\quad speed at $\kappa_{\max}$; delay spread", f"{hsr['v_kmh']:.0f}\\,km/h; {hsr['tau_us']:.1f}\\,$\\mu$s"),
        (r"\quad block; Doppler rate at 100\,m", f"{hsr['Tblk_ms']:.2f}\\,ms; {hsr['rho']:.4f} per block"),
        (r"\emph{V2V}: $f_\mathrm{c}$, $\Delta f$ ($\kappa_{\max}=1$)", r"60\,GHz, 15\,kHz"),
        (r"\quad relative speed; delay spread", f"{v2v['v_kmh']:.0f}\\,km/h; {v2v['tau_us']:.2f}\\,$\\mu$s"),
        (r"\quad block; Doppler rate at 20\,m", f"{1e3*v2v['Tblk_ms']:.1f}\\,$\\mu$s; {v2v['rho']:.5f} per block"),
    ]
    tex = ["% GENERATED by make_tables.py\n",
           "\\begin{table}[t]\n\\centering\n\\caption{Simulation Parameters and Physical Mapping}\n\\label{tab:params}\n",
           "\\footnotesize\n\\begin{tabular}{@{}ll@{}}\n\\toprule\n"]
    for a, b in rows:
        tex.append(f"{a} & {b} \\\\\n")
    tex.append("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (PAPER / "tab_params.tex").write_text("".join(tex))
    json.dump({"hsr": hsr, "v2v": v2v}, open(ROOT / "runs" / "physical_mapping.json", "w"), indent=1)
    print("".join(tex))




def robust_table(rho_run="e6_robust"):
    """Table II from runs/e6_robust (and the Doppler-rate rerun if present)."""
    import numpy as np
    from aggregate import summarize
    res, _ = summarize("e6_robust")
    try:
        rr, _ = summarize("e6_rho")
        res = [r for r in res if not r.get("model_rho")] + rr
    except FileNotFoundError:
        pass

    def find(**kw):
        for r in res:
            if all((r.get(k) if r.get(k) is not None else None) == v for k, v in kw.items()) and \
               all(k in kw or k not in ("rho_max", "window", "model_rho", "pn_var", "born_frac", "reacq_every", "P", "kappa_max", "cfo")
                   or r[k] in (None, False) for k in r):
                return r
        return None

    f = lambda x: "--" if x is None else f"{x:.2f}"
    rows = []
    base = find(rho_max=0.0)
    w0 = find(rho_max=0.0, window=6); m0 = find(rho_max=0.0, model_rho=True)
    rows.append(("Reference", f(base["tp_genie"]), f(base["tp_conv"]), f(base["tp_track"]),
                 f(w0["tp_track"] if w0 else None), f(m0["tp_track"] if m0 else None)))
    for cfo in (0.1, 0.3):
        r = find(cfo=cfo); rows.append((f"CFO ${cfo:g}$", f(r["tp_genie"]), f(r["tp_conv"]), f(r["tp_track"]), "--", "--"))
    for P in (2, 6, 8):
        r = find(P=P); rows.append((f"$P={P}$", f(r["tp_genie"]), f(r["tp_conv"]), f(r["tp_track"]), "--", "--"))
    for km in (1.0, 2.0):
        r = find(kappa_max=km); rows.append((f"$\\kappa_{{\\max}}={km:g}$", f(r["tp_genie"]), f(r["tp_conv"]), f(r["tp_track"]), "--", "--"))
    for rho in (0.002, 0.005, 0.01, 0.02):
        r = find(rho_max=rho); w = find(rho_max=rho, window=6); m = find(rho_max=rho, model_rho=True)
        rows.append((f"Drift ${rho:g}$", f(r["tp_genie"]), f(r["tp_conv"]), f(r["tp_track"]),
                     f(w["tp_track"] if w else None), f(m["tp_track"] if m else None)))
    for r in sorted([x for x in res if x.get("pn_var")], key=lambda x: x["pn_var"]):
        lw = r["pn_var"] * 512 / (2 * np.pi)
        ex = int(round(np.log10(lw))); mant = lw / 10 ** ex
        lwt = (f"10^{{{ex}}}" if abs(mant - 1) < 1e-9 else f"{mant:g}\\cdot10^{{{ex}}}")
        rows.append((f"PN ${lwt}$", f(r["tp_genie"]) + "$^\\dagger$",
                     f(r["tp_conv"]), f(r["tp_track"]), "--", "--"))
    for bf in (0.25, 0.5):
        r = find(born_frac=bf); w = find(born_frac=bf, reacq_every=1, window=8)
        rows.append((f"{int(100*bf)}\\% born", f(r["tp_genie"]), f(r["tp_conv"]), f(r["tp_track"]),
                     f(w["tp_track"] if w else None), "--"))
    tex = ["% GENERATED by make_tables.py from runs/e6_robust.jsonl\n",
           "\\begin{table}[t]\n\\centering\n\\caption{Throughput (bit/s/Hz) Under Impairments at 10\\,dB}\n\\label{tab:robust}\n",
           "\\footnotesize\n\\setlength{\\tabcolsep}{2.5pt}\n\\begin{tabular}{@{}lccccc@{}}\n\\toprule\n",
           "& Perfect & Embedded, & \\multicolumn{3}{c}{Proposed, $B_\\mathrm{p}=1$}\\\\\n\\cmidrule(l){4-6}\n",
           "Condition & CSI & every block & default & window & rate model\\\\\n\\midrule\n"]
    for row in rows:
        tex.append(" & ".join(row) + " \\\\\n")
    tex.append("\\bottomrule\n\\end{tabular}\n\n\\smallskip\n\\parbox{\\columnwidth}{\\scriptsize $^\\dagger$Knows the deterministic channel "
               "but not the random oscillator phase. Reference: $P=4$, $\\kappa_{\\max}=3$. CFO in subcarrier spacings; drift: Doppler rate in subcarrier spacings per block; "
               "PN: phase-noise linewidth relative to the subcarrier spacing; born: fraction of paths appearing during the frame. "
               "Window: sliding window of 6 blocks (8 with re-acquisition every block for path births). "
               f"Each entry averages {min(r['trials'] for r in res)} channel realizations.}}\n\\end{{table}}\n")
    (PAPER / "tab_robust.tex").write_text("".join(tex))
    print("".join(tex))


if __name__ == "__main__":
    import sys
    if "robust" in sys.argv[1:]:
        robust_table()
    else:
        main()
