"""Generate the pgfplots figures and data tables of the paper from runs/*.

Writes paper/fig_*.tex and paper/tab_paired.tex. Every coordinate comes from an
artifact; nothing is typed by hand. Run after the sweeps: python make_figures.py
"""
import json
from pathlib import Path

import numpy as np

from aggregate import summarize
from diagnostics import frames, paired

ROOT = Path(__file__).resolve().parent
RUNS = ROOT / "runs"
PAPER = ROOT / "paper"
PAPER.mkdir(exist_ok=True)
MAIN = "m_main"
N, NCP, BETA = 512, 8, 520 / 512
VU = (N * N - 1) / (12 * N * N)

STY = {
    "geniec":     ("gray!70!black", "dashed", "none", "Perfect CSI, pilot every block"),
    "convda":     ("gray!70!black", "solid", "square*", "Pilot every block, data-aided"),
    "sptrack":    ("teal!80!black", "solid", "diamond*", r"Superimposed $+$ tracker"),
    "interp":     ("violet!80!black", "densely dashed", "x", "Periodic pilots, interpolation"),
    "ptrack":     ("violet!80!black", "solid", "+", r"Periodic pilots $+$ tracker"),
    "genie":      ("black", "dashed", "none", "Perfect CSI"),
    "track1":     ("red!80!black", "solid", "*", r"Proposed, $B_\mathrm{p}{=}1$"),
    "track2":     ("red!55", "solid", "o", r"Proposed, $B_\mathrm{p}{=}2$"),
    "open":       ("blue!70!black", "densely dotted", "triangle*", "Open loop"),
    "ofdm":       ("orange!85!black", "dashdotted", "pentagon*", r"OFDM $+$ tracker"),
}


def rho_cr(L, E, b, P=4):
    """Decoupled benchmark, eq. (horizon) of the paper."""
    vL = BETA ** 2 * (L ** 2 - 1) / 12 + VU
    return P / (2 * L * E) * (2 + (BETA ** 2 * (b - (L - 1) / 2) ** 2 + VU) / vL)


def plot(key, pts, legend=True):
    c, ls, mk, lab = STY[key]
    coords = " ".join(f"({x:g},{y:.6g})" for x, y in pts if y is not None and np.isfinite(y))
    leg = f"\\addlegendentry{{{lab}}}\n" if legend else ""
    return (f"\\addplot[color={c}, {ls}, thick, mark={mk}, mark size=1.6pt, mark options={{solid}}] "
            f"coordinates {{{coords}}};\n{leg}")


def main_tables():
    """Per-SNR summaries of m_main: Bp=1 point, Bp=2 point, best open loop, best periodic."""
    res, _ = summarize(MAIN)
    A1 = {r["snr_db"]: r for r in res if r.get("Bp") == 1 and "tp_track" in r}
    A2 = {r["snr_db"]: r for r in res if r.get("Bp") == 2}
    snrs = sorted(A1)
    ol = {}
    for r in res:
        if "tp_openloop" in r and (r["snr_db"] not in ol or r["tp_openloop"] > ol[r["snr_db"]][0]):
            ol[r["snr_db"]] = (r["tp_openloop"], r["Bp"])
    ip = {s: max((A1[s]["tp_interp4"], 4), (A1[s]["tp_interp8"], 8)) for s in snrs}
    pt = {s: max((A1[s]["tp_ptrack4"], 4), (A1[s]["tp_ptrack8"], 8)) for s in snrs}
    return res, A1, A2, snrs, ol, ip, pt


def fig_main():
    res, A1, A2, snrs, ol, ip, pt = main_tables()
    tp = {
        "genie": [(s, A1[s]["tp_genie"]) for s in snrs],
        "track1": [(s, A1[s]["tp_track"]) for s in snrs],
        "track2": [(s, A2[s]["tp_track"]) for s in snrs],
        "geniec": [(s, A1[s]["tp_genie-conv"]) for s in snrs],
        "convda": [(s, A1[s]["tp_conv-da"]) for s in snrs],
        "sptrack": [(s, A1[s]["tp_sp-track"]) for s in snrs],
        "interp": [(s, ip[s][0]) for s in snrs],
        "ptrack": [(s, pt[s][0]) for s in snrs],
        "open": [(s, ol[s][0]) for s in snrs],
        "ofdm": [(s, A1[s]["tp_ofdm-track"]) for s in snrs],
    }
    nmin = min(A1[s]["trials"] for s in snrs)
    nmax = max(A1[s]["trials"] for s in snrs)
    hi = [s for s in snrs if A1[s]["trials"] == nmax]
    axis = ("\\begin{axis}[%s width=\\columnwidth, height=0.68\\columnwidth, xlabel={SNR (dB)}, "
            "ylabel={Throughput (bit/s/Hz)}, grid=both, grid style={black!12}, xmin=%g, xmax=%g, ymin=0, ymax=1, "
            "legend style={font=\\scriptsize, at={(0.985,0.015)}, anchor=south east, legend columns=1, "
            "fill=white, fill opacity=0.75, draw=black!40, draw opacity=0.7, text opacity=1, inner sep=1pt, "
            "row sep=-2.5pt, /tikz/every even column/.append style={column sep=3pt}}, legend cell align=left, "
            "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, title={%s}, "
            "title style={font=\\footnotesize, yshift=-4pt}]\n")
    tex = [f"% GENERATED by make_figures.py from runs/{MAIN} (same channel draws for every curve)\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n",
           axis % ("name=a,", min(snrs), max(snrs), "(a) pilot placement")]
    for k in ("genie", "track1", "geniec", "convda", "sptrack", "interp", "ptrack"):
        tex.append(plot(k, tp[k]))
    tex.append("\\end{axis}\n")
    tex.append(axis.replace("\\begin{axis}[%s", "\\begin{axis}[at={(a.south west)}, anchor=north west, yshift=-1.45cm, %s")
               % ("", min(snrs), max(snrs), "(b) tracking, pilot blocks and waveform"))
    for k in ("genie", "track1", "track2", "open", "ofdm"):
        tex.append(plot(k, tp[k]))
    tex.append("\\end{axis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Coded throughput versus SNR; all receivers see the same channel realizations. Periodic pilots use "
               "the best $K\\in\\{4,8\\}$ and open loop the best $B_\\mathrm{p}\\in\\{1,2,4,8\\}$ at each SNR.}\n"
               "\\label{fig:tp}\n\\end{figure}\n")
    (PAPER / "fig_tp.tex").write_text("".join(tex))

    # block error rate with 95% whole-frame bootstrap intervals (block errors cluster in
    # frames that lose lock, so blocks are not independent); a point without any block
    # error is marked on the lower edge
    keys = (("genie", "genie"), ("track1", "track"), ("convda", "conv-da"), ("sptrack", "sp-track"), ("ofdm", "ofdm-track"))
    spec, by = frames(MAIN)
    pidx = {g["snr_db"]: i for i, g in enumerate(spec["grid"]) if g.get("Bp") == 1}
    tex = [f"% GENERATED by make_figures.py from runs/{MAIN}\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n\\begin{semilogyaxis}[width=\\columnwidth, "
           "height=0.68\\columnwidth, xlabel={SNR (dB)}, ylabel={Block error rate}, grid=both, grid style={black!12}, "
           "xmin=%g, xmax=%g, ymin=1e-4, ymax=1, legend style={font=\\scriptsize, at={(0.015,0.015)}, anchor=south west, "
           "fill=white, fill opacity=0.75, draw=black!40, draw opacity=0.7, text opacity=1, inner sep=1pt, row sep=-2.5pt}, "
           "legend cell align=left, tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, "
           "error bars/y dir=both, error bars/y explicit, error bars/error bar style={thin, solid}, "
           "error bars/error mark options={rotate=90, mark size=1.2pt}]\n"
           % (min(snrs), max(snrs))]
    rng = np.random.default_rng(1)
    zeros, counts, cis = [], {}, {}
    for k, rx in keys:
        pts = []
        for s in snrs:
            rows = by[pidx[s]]
            e = np.array([sum(r[rx]["blerr"]) for r in rows], float)
            n = np.array([sum(1 for m in r[rx]["n"] if m > 0) for r in rows], float)
            ne, nb = int(e.sum()), int(n.sum())
            counts[(k, s)] = (ne, nb)
            if ne == 0:
                zeros.append((s, STY[k][0], 1.15e-4))
                continue
            idx = rng.integers(0, len(rows), (4000, len(rows)))
            bs = e[idx].sum(1) / n[idx].sum(1)
            lo, hi = np.percentile(bs, [2.5, 97.5])
            v = ne / nb
            cis[(k, s)] = (float(lo), float(hi))
            pts.append((s, v, v - max(lo, 1e-4), hi - v))
        c, ls, mk, lab = STY[k]
        coords = " ".join(f"({x:g},{y:.6g}) -= (0,{dl:.6g}) += (0,{dh:.6g})" for x, y, dl, dh in pts)
        tex.append(f"\\addplot[color={c}, {ls}, thick, mark={mk}, mark size=1.6pt, mark options={{solid}}] "
                   f"coordinates {{{coords}}};\n\\addlegendentry{{{lab}}}\n")
    for s, c, y in zeros:
        tex.append(f"\\addplot[color={c}, only marks, mark=triangle, mark options={{rotate=180, solid}}, mark size=2.2pt, "
                   f"forget plot] coordinates {{({s:g},{y:.4g})}};\n")
    tex.append("\\end{semilogyaxis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Block error rate of selected receivers of Fig.~\\ref{fig:tp}, with 95\\% bootstrap intervals over "
               "whole frames. Triangles on the lower edge: no block error observed.}"
               "\n\\label{fig:bler}\n\\end{figure}\n")
    (PAPER / "fig_bler.tex").write_text("".join(tex))
    json.dump({"best_open": [(s, ol[s][0], ol[s][1]) for s in snrs],
               "best_interp": [(s, ip[s][0], ip[s][1]) for s in snrs],
               "best_ptrack": [(s, pt[s][0], pt[s][1]) for s in snrs],
               "bler_counts": {f"{k}@{s}": v for (k, s), v in counts.items()},
               "bler_ci95": {f"{k}@{s}": v for (k, s), v in cis.items()}},
              open(RUNS / "fig_main_meta.json", "w"), indent=1)


def _pct(x):
    """Signed percentage with one decimal; two where one decimal would print as 0.0,
    so that the sign of an interval endpoint near zero stays visible."""
    return f"{x:+.2f}" if round(abs(x), 1) == 0 and x != 0 else f"{x:+.1f}"


def _ci(d):
    return f"${_pct(100 * d['ratio'])}$\\,[${_pct(100 * d['ratio_lo'])}$,${_pct(100 * d['ratio_hi'])}$]"


def tab_paired():
    """Paired frame-bootstrap 95% intervals of the proposed receiver's relative
    throughput difference to each reference at the high-trial SNR points."""
    res, A1, A2, snrs, ol, ip, pt = main_tables()
    spec, by = frames(MAIN)
    pidx = {(g["snr_db"], g.get("Bp")): i for i, g in enumerate(spec["grid"])}
    nmax = max(A1[s]["trials"] for s in snrs)
    key = [s for s in snrs if A1[s]["trials"] == nmax]
    refs = [("Perfect CSI", "genie"), ("Pilot every block, data-aided", "conv-da"),
            ("Periodic pilots, interpolation", "interp*"), ("Periodic pilots $+$ tracker", "ptrack*"),
            ("Superimposed $+$ tracker", "sp-track"), ("\\quad low latency ($K_\\mathrm{a}\\le4$)", "sp-track-ll"),
            ("OFDM $+$ tracker", "ofdm-track"), ("Proposed, hybrid aperture (ablation)", "track-hybrid")]
    out, rows_tex = {}, []
    for lab, rx in refs:
        cells = []
        for s in key:
            rows = by[pidx[(s, 1)]]
            rx_s = f"{rx[:-1]}{(pt if rx.startswith('ptrack') else ip)[s][1]}" if rx.endswith("*") else rx
            d = paired(rows, "track", rx_s, seed=int(s))
            out[f"{rx}@{s}"] = {**d, "rx": rx_s}
            cells.append(_ci(d))
        rows_tex.append(lab + " & " + " & ".join(cells) + " \\\\\n")
    cells = []
    for s in key:                      # open loop at its best Bp: its own grid point, same channel draws
        bp = ol[s][1]
        ra = {r["seed"]: r for r in by[pidx[(s, 1)]]}
        rb = {r["seed"]: r for r in by[pidx[(s, bp)]]}
        merged = [{**ra[k], "openloop_b": rb[k]["openloop"]} for k in ra if k in rb]
        d = paired(merged, "track", "openloop_b", seed=int(s))
        out[f"openloop@{s}"] = {**d, "Bp": bp}
        cells.append(_ci(d))
    rows_tex.insert(4, "Open loop & " + " & ".join(cells) + " \\\\\n")
    n = min(v["n"] for k, v in out.items() if not k.startswith("openloop"))
    n_ol = min(v["n"] for k, v in out.items() if k.startswith("openloop"))
    tex = [f"% GENERATED by make_figures.py from runs/{MAIN}\n",
           "\\begin{table*}[t]\n\\centering\n\\caption{Throughput of the Proposed Receiver Relative to Each Reference (\\%), "
           "With Paired 95\\% Bootstrap Intervals}\n\\label{tab:paired}\n\\footnotesize\n\\setlength{\\tabcolsep}{8pt}\n"
           "\\begin{tabular}{@{}l" + "c" * len(key) + "@{}}\n\\toprule\nReference & " +
           " & ".join(f"{s}\\,dB" for s in key) + " \\\\\n\\midrule\n"] + rows_tex + [
           "\\bottomrule\n\\end{tabular}\n\n\\smallskip\n\\parbox{0.8\\textwidth}{\\scriptsize Entries: "
           "$\\bar T_\\mathrm{proposed}/\\bar T_\\mathrm{ref}-1$ over "
           f"{n} channel realizations per SNR ({n_ol} for the open loop, whose best $B_\\mathrm{{p}}$ point has fewer); in brackets, the 2.5 and 97.5 percentiles over 4000 resamples of whole frames "
           "(all receivers of a frame resampled together). Positive: the proposed receiver is ahead. Best-of selections "
           "(periodic: $K$; open loop: $B_\\mathrm{p}$) are made on the evaluation channels and favor the reference; the intervals "
           "are pointwise and conditional on the selected settings.}\n\\end{table*}\n"]
    (PAPER / "tab_paired.tex").write_text("".join(tex))
    json.dump(out, open(RUNS / "paired.json", "w"), indent=1)


def fig_frame():
    res, _ = summarize("m_frame")
    tex = ["% GENERATED by make_figures.py from runs/m_frame.jsonl\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n"
           "\\begin{semilogxaxis}[width=\\columnwidth, height=0.52\\columnwidth, xlabel={Frame length $B$ (blocks)}, "
           "ylabel={Throughput (bit/s/Hz)}, log basis x=2, xtick={4,8,16,32,64}, xticklabels={4,8,16,32,64}, grid=both, grid style={black!12}, ymin=0, ymax=1, "
           "legend style={font=\\scriptsize, at={(0.5,-0.3)}, anchor=north, legend columns=2, cells={anchor=west}}, "
           "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}]\n"]
    for snr, fill in ((12, True), (6, False)):
        rr = sorted([r for r in res if r["snr_db"] == snr], key=lambda r: r["B"])
        for key, field in (("genie", "tp_genie"), ("track1", "tp_track"), ("open", "tp_openloop"), ("convda", "tp_conv-da")):
            c, ls, mk, lab = STY[key]
            mk2 = mk if fill else {"*": "o", "square*": "square", "triangle*": "triangle"}.get(mk, mk)
            coords = " ".join(f"({r['B']},{r[field]:.6g})" for r in rr)
            tex.append(f"\\addplot[color={c}, {ls}, thick, mark={mk2}, mark size=1.6pt, mark options={{solid}}] "
                       f"coordinates {{{coords}}};\n")
            if fill:
                if key == "open":
                    lab = r"Open loop, $B_\mathrm{p}{=}1$"
                tex.append(f"\\addlegendentry{{{lab}}}\n")
    n = min(r["trials"] for r in res)
    tex.append("\\end{semilogxaxis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Throughput versus frame length; the proposed and open-loop frames have one pilot block. Filled markers: 12\\,dB; "
               f"open markers: 6\\,dB. Each point averages {n} channel realizations.}}\n"
               "\\label{fig:frame}\n\\end{figure}\n")
    (PAPER / "fig_frame.tex").write_text("".join(tex))


def fig_theory():
    th = json.load(open(RUNS / "theory_check.json"))
    e2, e3, e4 = th["e2"], th["e3"], th["e4"]["rows"]
    cols = {1: "red!80!black", 2: "blue!70!black", 4: "teal!80!black"}
    leg = ("legend style={font=\\scriptsize, fill=white, fill opacity=0.7, draw=black!40, draw opacity=0.7, "
           "text opacity=1, inner sep=1.5pt, row sep=-1pt, cells={anchor=west}}, legend cell align=left")
    common = ("width=\\columnwidth, height=0.54\\columnwidth, grid=both, grid style={black!12}, "
              "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, "
              "title style={font=\\footnotesize, yshift=-3pt}, " + leg)
    tex = ["% GENERATED by make_figures.py from runs/theory_check.json\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n"
           f"\\begin{{axis}}[name=a, {common}, xlabel={{Per-block pilot SNR $\\gamma_1$ (dB)}}, "
           "ylabel={Probability}, ymin=0, ymax=1.02, xmin=-6, xmax=21, "
           "legend style={at={(0.98,0.03)}, anchor=south east}, title={(a) acquisition, Approximation~\\ref{prop:acq}}]\n"]
    for Bp in (1, 2, 4):
        rr = sorted([r for r in e2 if r["Bp"] == Bp], key=lambda r: r["gamma1_db"])
        tex.append(f"\\addplot[color={cols[Bp]}, only marks, mark=*, mark size=1.5pt, forget plot] coordinates {{"
                   + " ".join(f"({r['gamma1_db']},{r['p_cell']:.4f})" for r in rr) + "};\n")
        tex.append(f"\\addplot[color={cols[Bp]}, thick, forget plot] coordinates {{"
                   + " ".join(f"({r['gamma1_db']},{r['p_cell_formula']:.4f})" for r in rr) + "};\n")
        tex.append(f"\\addlegendimage{{color={cols[Bp]}, thick, mark=*, mark size=1.5pt}}\n")
        tex.append(f"\\addlegendentry{{$P_\\mathrm{{cell}}$, $B_\\mathrm{{p}}{{=}}{Bp}$}}\n")
    rr = sorted(e4, key=lambda r: r["gamma1_db"])
    tex.append("\\addplot[color=black, only marks, mark=o, mark size=1.8pt, forget plot] coordinates {"
               + " ".join(f"({r['gamma1_db']},{r['p_retained']:.4f})" for r in rr) + "};\n")
    tex.append("\\addplot[color=black, thick, densely dashed, forget plot] coordinates {"
               + " ".join(f"({r['gamma1_db']},{r['p_retained_formula']:.4f})" for r in rr) + "};\n")
    tex.append("\\addlegendimage{color=black, thick, densely dashed, mark=o, mark size=1.8pt, mark options={solid}}\n")
    tex.append("\\addlegendentry{$P_\\mathrm{ret}$, $B_\\mathrm{p}{=}1$}\n")
    tex.append("\\end{axis}\n")
    r20 = [r for r in e3 if r["gamma1_db"] == 20]
    lo = min(min(r["tr_emp"]) for r in r20)
    ymin = 10 ** (np.floor(np.log10(lo)) - 1)
    tex.append(f"\\begin{{semilogyaxis}}[at={{(a.south west)}}, anchor=north west, yshift=-1.6cm, {common}, "
               "xlabel={Predicted block $b'$}, ylabel={Prediction NMSE}, xmin=0, xmax=28, "
               f"ymin={ymin:g}, ymax=5, legend pos=south west, legend columns=2, "
               "title={(b) prediction, Theorem~\\ref{thm:pred}, $\\gamma_1=20$\\,dB}]\n")
    for r in r20:
        Bp = r["Bp"]
        tex.append(f"\\addplot[color={cols[Bp]}, only marks, mark=*, mark size=1.3pt, forget plot] coordinates {{"
                   + " ".join(f"({b},{v:.4g})" for b, v in zip(r["lag"], r["ol_emp"])) + "};\n")
        tex.append(f"\\addplot[color={cols[Bp]}, thick, forget plot] coordinates {{"
                   + " ".join(f"({b},{v:.4g})" for b, v in zip(r["lag"], r["ol_formula"]) if v <= 1) + "};\n")
        tex.append(f"\\addlegendimage{{color={cols[Bp]}, thick, mark=*, mark size=1.3pt}}\n")
        tex.append(f"\\addlegendentry{{open loop, $B_\\mathrm{{p}}{{=}}{Bp}$}}\n")
    r1 = [r for r in r20 if r["Bp"] == 1][0]
    tex.append("\\addplot[color=black, only marks, mark=square*, mark size=1.3pt, forget plot] coordinates {"
               + " ".join(f"({b},{v:.4g})" for b, v in zip(r1["tr_block"], r1["tr_emp"])) + "};\n")
    tex.append("\\addplot[color=black, thick, forget plot] coordinates {"
               + " ".join(f"({b},{v:.4g})" for b, v in zip(r1["tr_block"], r1["tr_formula"])) + "};\n")
    tex.append("\\addlegendimage{color=black, thick, mark=square*, mark size=1.3pt}\n")
    tex.append("\\addlegendentry{tracked, $B_\\mathrm{p}{=}1$}\n")
    tex.append("\\addplot[black!50, densely dashed, domain=0:28, samples=2, forget plot] {2};\n")
    tex.append("\\end{semilogyaxis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Validation of the analysis; markers: simulation, lines: approximations and bounds. "
               "(a) Correct-cell and retention probabilities. (b) Prediction NMSE of an isolated path "
               "(bounds drawn below one; dashed: random-phase level).}\n"
               "\\label{fig:theory}\n\\end{figure}\n")
    (PAPER / "fig_theory.tex").write_text("".join(tex))


def fig_diag():
    """Achieved prediction-error-to-noise ratio of the proposed receiver versus the
    benchmark of Corollary 2, and the matched-model control."""
    spec, by = frames(MAIN)
    cols = {6: "blue!70!black", 10: "teal!80!black", 16: "red!80!black"}
    tex = [f"% GENERATED by make_figures.py from runs/{MAIN}, runs/m_mismatch\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n"
           "\\begin{axis}[width=\\columnwidth, height=0.62\\columnwidth, xlabel={Predicted block $b$}, "
           "ylabel={$\\rho(b)$ (dB)}, grid=both, grid style={black!12}, xmin=1, xmax=15, ymin=-40, ymax=0, "
           "legend style={font=\\scriptsize, at={(0.5,0.015)}, anchor=south, legend columns=2, fill=white, "
           "fill opacity=0.75, draw=black!40, draw opacity=0.7, text opacity=1, inner sep=1pt, row sep=-2.5pt, "
           "/tikz/every even column/.append style={column sep=4pt}}, legend cell align=left, "
           "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}]\n"]
    meta = {}
    for i, g in enumerate(spec["grid"]):
        if g.get("Bp") != 1 or g["snr_db"] not in cols:
            continue
        R = np.array([r["diag-track"]["rho_pred"] for r in by[i] if "diag-track" in r])
        med = 10 * np.log10(np.median(R, 0))
        meta[f"phys@{g['snr_db']}"] = med.tolist()
        tex.append(f"\\addplot[color={cols[g['snr_db']]}, thick, mark=*, mark size=1.2pt] coordinates {{"
                   + " ".join(f"({b},{med[b]:.3f})" for b in range(1, R.shape[1])) + "};\n")
        tex.append(f"\\addlegendentry{{Proposed, {g['snr_db']}\\,dB}}\n")
    sm, bm = frames("m_mismatch")
    for i, g in enumerate(sm["grid"]):
        if g.get("circular") and g["snr_db"] == 16:
            R = np.array([r["diag-track"]["rho_pred"] for r in bm[i] if "diag-track" in r])
            med = 10 * np.log10(np.median(R, 0))
            meta["circ@16"] = med.tolist()
            tex.append("\\addplot[color=red!80!black, densely dashed, thick, mark=o, mark size=1.2pt] coordinates {"
                       + " ".join(f"({b},{med[b]:.3f})" for b in range(1, R.shape[1])) + "};\n")
            tex.append("\\addlegendentry{Matched model, 16\\,dB}\n")
    tex.append("\\addplot[black, thick] coordinates {"
               + " ".join(f"({b},{10 * np.log10(rho_cr(b, N, b)):.3f})" for b in range(1, 16)) + "};\n")
    tex.append("\\addlegendentry{Benchmark~\\eqref{eq:horizon}, $L=b$}\n")
    tex.append("\\end{axis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Median prediction-error-to-noise ratio of the channel that first detects block $b$, with every block "
               "counted, against the benchmark for $b$ known blocks, a mean-square bound independent of the SNR. "
               "Matched model: the channel follows the receiver's circular delay model.}\n"
               "\\label{fig:diag}\n\\end{figure}\n")
    (PAPER / "fig_diag.tex").write_text("".join(tex))
    json.dump(meta, open(RUNS / "fig_diag_meta.json", "w"), indent=1)


def fig_two():
    """Two paths: joint versus decoupled benchmark, and receiver throughput, versus
    the Doppler separation."""
    ck = json.load(open(RUNS / "checks.json"))["k6"]
    res, _ = summarize("m_two")
    cols = {1: "red!80!black", 2: "orange!85!black", 4: "teal!80!black", 8: "blue!70!black"}
    leg = ("fill=white, fill opacity=0.75, draw=black!40, draw opacity=0.7, text opacity=1, inner sep=1pt, row sep=-2.5pt, "
           "/tikz/every even column/.append style={column sep=4pt}")
    tex = ["% GENERATED by make_figures.py from runs/checks.json (k6) and runs/m_two\n",
           "\\begin{figure}[t]\n\\centering\n\\begin{tikzpicture}\n"
           "\\begin{semilogxaxis}[name=a, width=\\columnwidth, height=0.6\\columnwidth, xlabel={Doppler separation $\\Delta\\kappa$}, "
           "ylabel={$\\rho_\\mathrm{J}/\\rho_\\mathrm{CR}$ (dB)}, grid=both, grid style={black!12}, xmin=0.02, xmax=2, ymin=-1, ymax=19, "
           f"legend style={{font=\\scriptsize, at={{(0.5,0.985)}}, anchor=north, legend columns=5, {leg}, /tikz/every even column/.append style={{column sep=1.5pt}}}}, legend cell align=left, "
           "legend image code/.code={\\draw[mark repeat=2, mark phase=2] plot coordinates {(0cm,0cm) (0.2cm,0cm) (0.4cm,0cm)};}, "
           "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, "
           "title={(a) joint versus decoupled benchmark, next block}, title style={font=\\footnotesize, yshift=-3pt}]\n"]
    for L in (1, 2, 4, 8):
        rr = sorted([r for r in ck if r["dl"] == 0.0 and r["L"] == L], key=lambda r: r["dk"])
        band = [(r["dk"], r["ratio_db_q75"]) for r in rr] + [(r["dk"], r["ratio_db_q25"]) for r in rr[::-1]]
        tex.append(f"\\addplot[fill={cols[L]}, fill opacity=0.13, draw=none, forget plot] coordinates {{"
                   + " ".join(f"({x:g},{y:.3f})" for x, y in band) + "} -- cycle;\n")
        tex.append(f"\\addplot[color={cols[L]}, thick, mark=*, mark size=1.1pt] coordinates {{"
                   + " ".join(f"({r['dk']:g},{r['ratio_db_median']:.3f})" for r in rr) + "};\n")
        tex.append(f"\\addlegendentry{{$L{{=}}{L}$}}\n")
    rr = sorted([r for r in ck if r["dl"] == 1.0 and r["L"] == 1], key=lambda r: r["dk"])
    tex.append("\\addplot[color=black, densely dashed, thick] coordinates {"
               + " ".join(f"({r['dk']:g},{r['ratio_db_median']:.3f})" for r in rr) + "};\n")
    tex.append("\\addlegendentry{$L{=}1$, $\\Delta\\ell{=}1$}\n")
    tex.append("\\end{semilogxaxis}\n")
    tex.append("\\begin{semilogxaxis}[at={(a.south west)}, anchor=north west, yshift=-1.45cm, width=\\columnwidth, "
               "height=0.56\\columnwidth, xlabel={Doppler separation $\\Delta\\kappa$}, ylabel={Throughput (bit/s/Hz)}, "
               "grid=both, grid style={black!12}, xmin=0.04, xmax=2, ymin=0, ymax=1, "
               f"legend style={{font=\\scriptsize, at={{(0.985,0.015)}}, anchor=south east, legend columns=2, {leg}}}, "
               "legend cell align=left, legend image code/.code={\\draw[mark repeat=2, mark phase=2] plot coordinates {(0cm,0cm) (0.25cm,0cm) (0.5cm,0cm)};}, "
               "tick label style={font=\\footnotesize}, label style={font=\\footnotesize}, "
               "title={(b) two equal-power paths, 12\\,dB}, title style={font=\\footnotesize, yshift=-3pt}]\n")
    for dl, ls in ((0.0, "solid"), (1.0, "densely dashed")):
        rr = sorted([r for r in res if r["tp_dl"] == dl], key=lambda r: r["tp_dk"])
        for rx, c, mk in (("genie", "black", "none"), ("track", "red!80!black", "*"), ("conv-da", "gray!70!black", "square*")):
            tex.append(f"\\addplot[color={c}, {ls}, thick, mark={mk}, mark size=1.4pt, mark options={{solid}}] coordinates {{"
                       + " ".join(f"({r['tp_dk']:g},{r['tp_' + rx]:.4f})" for r in rr) + "};\n")
            lab = {"genie": "Perfect CSI", "track": "Proposed", "conv-da": "Pilot every block"}[rx]
            tex.append(f"\\addlegendentry{{{lab}, $\\Delta\\ell{{=}}{int(dl)}$}}\n")
    n = min(r["trials"] for r in res)
    nd = min(r["draws"] for r in ck)
    tex.append("\\end{semilogxaxis}\n\\end{tikzpicture}\n")
    tex.append("\\caption{Two paths $\\Delta\\ell$ samples apart in delay and $\\Delta\\kappa$ in Doppler. (a) Joint over decoupled "
               "benchmark~\\eqref{eq:rho} after $L$ known blocks, known integer delays, $\\Delta\\ell=0$ unless marked: median and interquartile range over "
               f"{nd} random geometries and training data. (b) Coded throughput, Rayleigh paths of equal average power, "
               f"{n} channel realizations per point.}}\n\\label{{fig:two}}\n\\end{{figure}}\n")
    (PAPER / "fig_two.tex").write_text("".join(tex))


if __name__ == "__main__":
    import sys
    fns = {"theory": fig_theory, "main": fig_main, "paired": tab_paired, "frame": fig_frame,
           "diag": fig_diag, "two": fig_two}
    for f in (sys.argv[1:] or list(fns)):
        try:
            fns[f]()
            print(f, "ok")
        except Exception as e:  # noqa: BLE001
            print(f, "FAILED:", repr(e))
