"""Generate paper/tab_params.tex (simulation parameters and physical mapping)
from engine.Config, the main sweep spec and the codec, so the printed
parameters cannot drift from the simulated ones."""
import json
from pathlib import Path

from coding import BlockCode, K, G
from engine import Config
from mbafdm import MBAFDM

ROOT = Path(__file__).resolve().parent
PAPER = ROOT / "paper"
PAPER.mkdir(exist_ok=True)
C0 = 299_792_458.0


def physical(fc, df, N, Ncp, kmax, ell_max, d):
    Ts = 1 / (N * df)
    lam = C0 / fc
    v = kmax * df * lam
    Tblk = (N + Ncp) * Ts
    rate = v ** 2 / (lam * d)                         # Doppler rate bound, Hz/s
    return dict(v_kmh=3.6 * v, tau_us=1e6 * ell_max * Ts, Tblk_ms=1e3 * Tblk,
                rho=rate * Tblk / df, bw_mhz=N * df / 1e6, frame16_ms=16e3 * Tblk, frame64_ms=64e3 * Tblk)


def main():
    spec = json.load(open(ROOT / "specs" / "m_main.json"))
    cfg = Config(**{k: v for k, v in spec["base"].items() if k != "receivers"})
    ck = json.load(open(ROOT / "runs" / "checks.json"))["k5"]
    S = MBAFDM(N=cfg.N, Ncp=cfg.Ncp, alpha_max=cfg.alpha_max, xi=cfg.xi, ell_max=cfg.ell_max)
    from mbtrack import Tracker
    _T = Tracker(S)
    import inspect
    assert inspect.signature(Tracker.reacquire).parameters["M"].default == 64
    kp = BlockCode(S.data_idx.size).k_payload
    kd = BlockCode(S.N).k_payload
    hsr = physical(5.9e9, 1e3, cfg.N, cfg.Ncp, cfg.kappa_max, cfg.ell_max, 100.0)
    v2v = physical(60e9, 15e3, cfg.N, cfg.Ncp, 1.0, cfg.ell_max, 20.0)
    rows = [
        (r"Chirps $N$, CP $N_\mathrm{cp}$, $\beta$", f"{cfg.N}, {cfg.Ncp}, {S.beta:.4f}"),
        (r"$\alpha_{\max}$, $\xi$, $Q$, $\ell_{\max}$, $\kappa_{\max}$", f"{cfg.alpha_max}, {cfg.xi}, {S.Q}, {cfg.ell_max}, {cfg.kappa_max:g}"),
        (r"Reserved $|\mathcal{Z}|$, pilot energy $E_\mathrm{p}$", f"{len(S.zero_set)} chirps, {S.Ep:.0f}"),
        (r"Paths $P$ (estimated, cap $P_{\max}$)", f"{cfg.P} ({cfg.P_max})"),
        (r"Delays", r"$\mathcal{U}[0,\ell_{\max}-\tfrac12]$, fractional"),
        (r"Doppler", r"$\kappa_{\max}\cos\vartheta$, $\vartheta$ uniform"),
        (r"Power-delay profile", fr"$\propto e^{{-\ell/{cfg.tau_rms:g}}}$, Rayleigh gains"),
        (r"RMS delay spread, realized (samples)", fr"median {ck['median']:.1f}, 90\% {ck['p90']:.1f}"),
        (r"Frame", fr"$B={cfg.B}$ blocks"),
        (r"Code (rate 1/2)", fr"memory {K - 1}, ({G[0]:o},{G[1]:o})$_8$, zero tail"),
        (r"CRC-16", r"0x1021, init.\ 0xFFFF"),
        (r"Payload per pilot / data block", f"{kp} / {kd} bits"),
        (r"$P_\mathrm{fa}$; re-acq.\ period $R$; retries", fr"$10^{{-3}}$; {cfg.reacq_every} blocks; {_T.retries}"),
        (r"Re-acq.\ $W_\mathrm{r}$, $M_\mathrm{os}$, $\kappa_\mathrm{s}$", fr"{_T.reacq_window}, 64, {cfg.kappa_max + 0.5:g}"),
        (r"\emph{HSR}: $f_\mathrm{c}$, $\Delta f$", r"5.9\,GHz, 1\,kHz"),
        (r"\quad speed; max.\ delay (bound)", f"{hsr['v_kmh']:.0f}\\,km/h; {hsr['tau_us']:.1f}\\,$\\mu$s"),
        (r"\quad block; frame ($B=16$, 64)", f"{hsr['Tblk_ms']:.2f}\\,ms; {hsr['frame16_ms']:.2f}, {hsr['frame64_ms']:.0f}\\,ms"),
        (r"\quad Doppler rate at 100\,m", f"{hsr['rho']:.4f} per block"),
        (r"\emph{V2V}: $f_\mathrm{c}$, $\Delta f$ ($\kappa_{\max}=1$)", r"60\,GHz, 15\,kHz"),
        (r"\quad relative speed; max.\ delay (bound)", f"{v2v['v_kmh']:.0f}\\,km/h; {v2v['tau_us']:.2f}\\,$\\mu$s"),
        (r"\quad block; frame ($B=16$)", f"{1e3*v2v['Tblk_ms']:.1f}\\,$\\mu$s; {v2v['frame16_ms']:.2f}\\,ms"),
        (r"\quad Doppler rate at 20\,m", f"{v2v['rho']:.5f} per block"),
    ]
    tex = ["% GENERATED by make_tables.py\n",
           "\\begin{table}[t]\n\\centering\n\\caption{Simulation Parameters and Physical Mapping}\n\\label{tab:params}\n",
           "\\footnotesize\n\\setlength{\\tabcolsep}{2pt}\n\\begin{tabular}{@{}ll@{}}\n\\toprule\n"]
    for a, b in rows:
        tex.append(f"{a} & {b} \\\\\n")
    tex.append("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (PAPER / "tab_params.tex").write_text("".join(tex))
    json.dump({"hsr": hsr, "v2v": v2v}, open(ROOT / "runs" / "physical_mapping.json", "w"), indent=1)
    print("".join(tex))




def robust_table():
    """Table of throughput under impairments from runs/m_robust."""
    import numpy as np
    from aggregate import summarize
    res, _ = summarize("m_robust")
    VARS = ("rho_max", "window", "model_rho", "pn_var", "born_frac", "reacq_every", "P", "kappa_max", "cfo")

    def find(**kw):
        for r in res:
            if all(r.get(k) == v for k, v in kw.items()) and \
               all(k in kw or r.get(k) in (None, False) for k in VARS if k in r):
                return r
        return None

    f = lambda x: "--" if x is None else f"{x:.2f}"
    g = lambda r, k: None if (r is None or f"tp_{k}" not in r) else r[f"tp_{k}"]
    rows = []

    def row(label, base, w=None, m=None, genie_det=False):
        gen = f(g(base, "genie")) + (f" ({f(g(base, 'genie-det'))}$^\\dagger$)" if genie_det else "")
        rows.append((label, gen, f(g(base, "conv-da")), f(g(base, "track")), f(g(w, "track")), f(g(m, "track")),
                     f(g(base, "ptrack4"))))
    base = find(rho_max=0.0)
    row("Reference", base, find(rho_max=0.0, window=6), find(rho_max=0.0, model_rho=True))
    for cfo in (0.1, 0.3):
        row(f"CFO ${cfo:g}$", find(cfo=cfo))
    for P in (2, 6, 8):
        row(f"$P={P}$", find(P=P))
    for km in (1.0, 2.0):
        row(f"$\\kappa_{{\\max}}={km:g}$", find(kappa_max=km))
    for rho in (0.002, 0.005, 0.01, 0.02):
        row(f"Drift ${rho:g}$", find(rho_max=rho), find(rho_max=rho, window=6), find(rho_max=rho, model_rho=True))
    for r in sorted([x for x in res if x.get("pn_var") and "tp_genie" in x], key=lambda x: x["pn_var"]):
        lw = r["pn_var"] * 512 / (2 * np.pi)
        ex = int(np.floor(np.log10(lw) + 1e-9)); mant = lw / 10 ** ex
        lwt = (f"10^{{{ex}}}" if abs(mant - 1) < 1e-9 else f"{mant:g}\\cdot10^{{{ex}}}")
        row(f"PN ${lwt}$", r, genie_det=True)
    for bf in (0.25, 0.5):
        row(f"{int(100*bf)}\\% born", find(born_frac=bf), find(born_frac=bf, reacq_every=1, window=8))
    n = min(r["trials"] for r in res)
    se = [r["tp_track_se"] for r in res if "tp_track_se" in r]
    tex = ["% GENERATED by make_tables.py from runs/m_robust.jsonl\n",
           "\\begin{table}[t]\n\\centering\n\\caption{Throughput (bit/s/Hz) Under Impairments at 10\\,dB}\n\\label{tab:robust}\n",
           "\\footnotesize\n\\setlength{\\tabcolsep}{1.6pt}\n\\begin{tabular}{@{}lcccccc@{}}\n\\toprule\n",
           "& Perfect & Pilot every & \\multicolumn{3}{c}{Proposed, $B_\\mathrm{p}=1$} & Periodic\\\\\n\\cmidrule(lr){4-6}\n",
           "Condition & CSI & block & default & window & rate & +tracker\\\\\n\\midrule\n"]
    for r in rows:
        tex.append(" & ".join(r) + " \\\\\n")
    tex.append("\\bottomrule\n\\end{tabular}\n\n\\smallskip\n\\parbox{\\columnwidth}{\\scriptsize "
               "Reference: $P=4$, $\\kappa_{\\max}=3$; all receivers of a condition see the same channel realizations. CFO in subcarrier spacings. "
               "Drift: each path's Doppler rate drawn uniformly in $[-\\eta_{\\max},\\eta_{\\max}]$, $\\eta_{\\max}$ given in subcarrier spacings per block. "
               "PN: Wiener phase noise of normalized linewidth $\\lambda_\\mathrm{PN}=\\Delta\\nu_\\mathrm{PN}/\\Delta f$ (increment variance "
               "$2\\pi\\lambda_\\mathrm{PN}/N$ per sample), one trajectory shared by all receivers of a trial; perfect CSI knows it, "
               "$^\\dagger$knows only the deterministic channel. Born: a fraction of the paths, chosen at random, appears at a block drawn "
               "uniformly from $B_\\mathrm{p}+1$ to $B-1$ and is absent before. Pilot every block: data-aided. Window: sliding window of 6 blocks "
               "(8 with re-acquisition every block for path births); rate: Doppler-rate model. Periodic + tracker: a pilot block every "
               "4 blocks with the proposed tracker. "
               f"Each entry averages {n} channel realizations; the standard errors of the proposed receiver's entries are "
               f"{min(se):.2f}--{max(se):.2f}\\,bit/s/Hz.}}\n\\end{{table}}\n")
    (PAPER / "tab_robust.tex").write_text("".join(tex))
    print("".join(tex))


if __name__ == "__main__":
    import sys
    if "robust" in sys.argv[1:]:
        robust_table()
    else:
        main()
